@Library('mirrorfly') _

// For Android: Use buildDefaultAndroidPipeline() instead of buildDefaultIOSPipeline()
com.contus.cd.Pipeline.builder(this, steps)
        .buildUIKITIOSSamplePipeline(false, true) //Specific Pipeline
        .execute()